config/routes.rb
Rails.application.routes.draw do
  resources :name_ratings
  resources :baby_name_options
  resources :baby_profiles
  get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
  root 'baby_profiles#index'
  

  resources :users
end

app/models/name_rating.rb
class NameRating < ApplicationRecord
  belongs_to :baby_name_option
end

app/controllers/name_ratings_controller.rb
class NameRatingsController < ApplicationController
  before_action :set_name_rating, only: %i[ show edit update destroy ]

  # GET /name_ratings or /name_ratings.json
  def index
    @name_ratings = NameRating.all
  end

  # GET /name_ratings/1 or /name_ratings/1.json
  def show
  end

  # GET /name_ratings/new
  def new
    @name_rating = NameRating.new
  end

  # GET /name_ratings/1/edit
  def edit
  end

  # POST /name_ratings or /name_ratings.json
  def create
    @name_rating = NameRating.new(name_rating_params)

    respond_to do |format|
      if @name_rating.save
        format.html { redirect_to name_rating_url(@name_rating), notice: "Name rating was successfully created." }
        format.json { render :show, status: :created, location: @name_rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @name_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /name_ratings/1 or /name_ratings/1.json
  def update
    respond_to do |format|
      if @name_rating.update(name_rating_params)
        format.html { redirect_to name_rating_url(@name_rating), notice: "Name rating was successfully updated." }
        format.json { render :show, status: :ok, location: @name_rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @name_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /name_ratings/1 or /name_ratings/1.json
  def destroy
    @name_rating.destroy!

    respond_to do |format|
      format.html { redirect_to name_ratings_url, notice: "Name rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name_rating
      @name_rating = NameRating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_rating_params
      params.require(:name_rating).permit(:baby_name_option_id, :factor, :rating)
    end
end

app/helpers/name_ratings_helper.rb
module NameRatingsHelper
end

app/views/name_ratings/_form.html.erb
<%= form_with(model: name_rating) do |form| %>
  <% if name_rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name_rating.errors.count, "error") %> prohibited this name_rating from being saved:</h2>

      <ul>
        <% name_rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :baby_name_option_id, style: "display: block" %>
    <%= form.text_field :baby_name_option_id %>
  </div>

  <div>
    <%= form.label :factor, style: "display: block" %>
    <%= form.text_field :factor %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/name_ratings/_name_rating.html.erb
<div id="<%= dom_id name_rating %>">
  <p>
    <strong>Baby name option:</strong>
    <%= name_rating.baby_name_option_id %>
  </p>

  <p>
    <strong>Factor:</strong>
    <%= name_rating.factor %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= name_rating.rating %>
  </p>

</div>

app/views/name_ratings/edit.html.erb
<h1>Editing name rating</h1>

<%= render "form", name_rating: @name_rating %>

<br>

<div>
  <%= link_to "Show this name rating", @name_rating %> |
  <%= link_to "Back to name ratings", name_ratings_path %>
</div>

app/views/name_ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Name ratings</h1>

<div id="name_ratings">
  <% @name_ratings.each do |name_rating| %>
    <%= render name_rating %>
    <p>
      <%= link_to "Show this name rating", name_rating %>
    </p>
  <% end %>
</div>

<%= link_to "New name rating", new_name_rating_path %>

app/views/name_ratings/new.html.erb
<h1>New name rating</h1>

<%= render "form", name_rating: @name_rating %>

<br>

<div>
  <%= link_to "Back to name ratings", name_ratings_path %>
</div>

app/views/name_ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @name_rating %>

<div>
  <%= link_to "Edit this name rating", edit_name_rating_path(@name_rating) %> |
  <%= link_to "Back to name ratings", name_ratings_path %>

  <%= button_to "Destroy this name rating", @name_rating, method: :delete %>
</div>