config/routes.rb
Rails.application.routes.draw do
  resources :name_ratings
  resources :baby_name_options
  resources :baby_profiles
  get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
  root 'baby_profiles#index'
  

  resources :users
end

app/models/baby_name_option.rb
class BabyNameOption < ApplicationRecord
  belongs_to :baby_profile
end

app/controllers/baby_name_options_controller.rb
class BabyNameOptionsController < ApplicationController
  before_action :set_baby_name_option, only: %i[ show edit update destroy ]

  # GET /baby_name_options or /baby_name_options.json
  def index
    @baby_name_options = BabyNameOption.all
  end

  # GET /baby_name_options/1 or /baby_name_options/1.json
  def show
  end

  # GET /baby_name_options/new
  def new
    @baby_name_option = BabyNameOption.new
  end

  # GET /baby_name_options/1/edit
  def edit
  end

  # POST /baby_name_options or /baby_name_options.json
  def create
    @baby_name_option = BabyNameOption.new(baby_name_option_params)

    respond_to do |format|
      if @baby_name_option.save
        format.html { redirect_to baby_name_option_url(@baby_name_option), notice: "Baby name option was successfully created." }
        format.json { render :show, status: :created, location: @baby_name_option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @baby_name_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baby_name_options/1 or /baby_name_options/1.json
  def update
    respond_to do |format|
      if @baby_name_option.update(baby_name_option_params)
        format.html { redirect_to baby_name_option_url(@baby_name_option), notice: "Baby name option was successfully updated." }
        format.json { render :show, status: :ok, location: @baby_name_option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @baby_name_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baby_name_options/1 or /baby_name_options/1.json
  def destroy
    @baby_name_option.destroy!

    respond_to do |format|
      format.html { redirect_to baby_name_options_url, notice: "Baby name option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby_name_option
      @baby_name_option = BabyNameOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_name_option_params
      params.require(:baby_name_option).permit(:name, :baby_profile_id)
    end
end

app/helpers/baby_name_options_helper.rb
module BabyNameOptionsHelper
end

app/views/baby_name_options/_baby_name_option.html.erb
<div id="<%= dom_id baby_name_option %>">
  <p>
    <strong>Name:</strong>
    <%= baby_name_option.name %>
  </p>

  <p>
    <strong>Baby profile:</strong>
    <%= baby_name_option.baby_profile_id %>
  </p>

</div>

app/views/baby_name_options/_form.html.erb
<%= form_with(model: baby_name_option) do |form| %>
  <% if baby_name_option.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(baby_name_option.errors.count, "error") %> prohibited this baby_name_option from being saved:</h2>

      <ul>
        <% baby_name_option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :baby_profile_id, style: "display: block" %>
    <%= form.text_field :baby_profile_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/baby_name_options/edit.html.erb
<h1>Editing baby name option</h1>

<%= render "form", baby_name_option: @baby_name_option %>

<br>

<div>
  <%= link_to "Show this baby name option", @baby_name_option %> |
  <%= link_to "Back to baby name options", baby_name_options_path %>
</div>

app/views/baby_name_options/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Baby name options</h1>

<div id="baby_name_options">
  <% @baby_name_options.each do |baby_name_option| %>
    <%= render baby_name_option %>
    <p>
      <%= link_to "Show this baby name option", baby_name_option %>
    </p>
  <% end %>
</div>

<%= link_to "New baby name option", new_baby_name_option_path %>

app/views/baby_name_options/new.html.erb
<h1>New baby name option</h1>

<%= render "form", baby_name_option: @baby_name_option %>

<br>

<div>
  <%= link_to "Back to baby name options", baby_name_options_path %>
</div>

app/views/baby_name_options/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @baby_name_option %>

<div>
  <%= link_to "Edit this baby name option", edit_baby_name_option_path(@baby_name_option) %> |
  <%= link_to "Back to baby name options", baby_name_options_path %>

  <%= button_to "Destroy this baby name option", @baby_name_option, method: :delete %>
</div>