config/routes.rb
Rails.application.routes.draw do
  resources :name_ratings
  resources :baby_name_options
  resources :baby_profiles
  get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
  root 'baby_profiles#index'
  

  resources :users
end

app/models/baby_profile.rb
class BabyProfile < ApplicationRecord
    has_many :baby_name_options, dependent: :destroy      
end

app/controllers/baby_profiles_controller.rb
class BabyProfilesController < ApplicationController
  before_action :set_baby_profile, only: %i[ show edit update destroy ]

  # GET /baby_profiles or /baby_profiles.json
  def index
    @baby_profiles = BabyProfile.all
  end

  # GET /baby_profiles/1 or /baby_profiles/1.json
  def show
  end

  # GET /baby_profiles/new
  def new
    @baby_profile = BabyProfile.new
  end

  # GET /baby_profiles/1/edit
  def edit
  end

  # POST /baby_profiles or /baby_profiles.json
  def create
    @baby_profile = BabyProfile.new(baby_profile_params)

    respond_to do |format|
      if @baby_profile.save
        format.html { redirect_to baby_profile_url(@baby_profile), notice: "Baby profile was successfully created." }
        format.json { render :show, status: :created, location: @baby_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @baby_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baby_profiles/1 or /baby_profiles/1.json
  def update
    respond_to do |format|
      if @baby_profile.update(baby_profile_params)
        format.html { redirect_to baby_profile_url(@baby_profile), notice: "Baby profile was successfully updated." }
        format.json { render :show, status: :ok, location: @baby_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @baby_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baby_profiles/1 or /baby_profiles/1.json
  def destroy
    @baby_profile.destroy!

    respond_to do |format|
      format.html { redirect_to baby_profiles_url, notice: "Baby profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby_profile
      @baby_profile = BabyProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_profile_params
      params.require(:baby_profile).permit(:gender, :mothers_name, :fathers_name, :expected_date, :description)
    end
end

app/helpers/baby_profiles_helper.rb
module BabyProfilesHelper
end

app/views/baby_profiles/_baby_profile.html.erb
<div id="<%= dom_id baby_profile %>">
  <p>
    <strong>Gender:</strong>
    <%= baby_profile.gender %>
  </p>

  <p>
    <strong>Mothers name:</strong>
    <%= baby_profile.mothers_name %>
  </p>

  <p>
    <strong>Fathers name:</strong>
    <%= baby_profile.fathers_name %>
  </p>

  <p>
    <strong>Expected date:</strong>
    <%= baby_profile.expected_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= baby_profile.description %>
  </p>

</div>

app/views/baby_profiles/_form.html.erb
<%= form_with(model: baby_profile) do |form| %>
  <% if baby_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(baby_profile.errors.count, "error") %> prohibited this baby_profile from being saved:</h2>

      <ul>
        <% baby_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :mothers_name, style: "display: block" %>
    <%= form.text_field :mothers_name %>
  </div>

  <div>
    <%= form.label :fathers_name, style: "display: block" %>
    <%= form.text_field :fathers_name %>
  </div>

  <div>
    <%= form.label :expected_date, style: "display: block" %>
    <%= form.date_field :expected_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/baby_profiles/edit.html.erb
<h1>Editing baby profile</h1>

<%= render "form", baby_profile: @baby_profile %>

<br>

<div>
  <%= link_to "Show this baby profile", @baby_profile %> |
  <%= link_to "Back to baby profiles", baby_profiles_path %>
</div>

app/views/baby_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Baby profiles</h1>

<div id="baby_profiles">
  <% @baby_profiles.each do |baby_profile| %>
    <%= render baby_profile %>
    <p>
      <%= link_to "Show this baby profile", baby_profile %>
    </p>
  <% end %>
</div>

<%= link_to "New baby profile", new_baby_profile_path %>

app/views/baby_profiles/new.html.erb
<h1>New baby profile</h1>

<%= render "form", baby_profile: @baby_profile %>

<br>

<div>
  <%= link_to "Back to baby profiles", baby_profiles_path %>
</div>

app/views/baby_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @baby_profile %>

<div>
  <%= link_to "Edit this baby profile", edit_baby_profile_path(@baby_profile) %> |
  <%= link_to "Back to baby profiles", baby_profiles_path %>

  <%= button_to "Destroy this baby profile", @baby_profile, method: :delete %>
</div>