config/routes.rb
Rails.application.routes.draw do
  resources :name_ratings
  resources :baby_name_options
  resources :baby_profiles
  get 'pages/home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "users#index"
  root 'baby_profiles#index'
  

  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = 'User was successfully created.'
			redirect_to @user
		else
			flash[:error] = @user.errors.full_messages.join(', ')
			render :new, status: :unprocessable_entity
		end
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render :edit, status: :unprocessable_entity
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end
	  
	private
	
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
	<div>
		<%= form.label :username %><br>
		<%= form.text_field :username %>
		<% user.errors.full_messages_for(:username).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	<div>
		<%= form.label :email %><br>
		<%= form.text_area :email %><br>
		<% user.errors.full_messages_for(:email).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	<div>
		<%= form.label :password %><br>
		<%= form.text_area :password %><br>
		<% user.errors.full_messages_for(:password).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	
	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if @users.nil? %>
	<p>No users found.</p>
<% else %>
<ul>
	<% @users.each do |user| %>
	<li>
		<%= link_to user.username, user %>
	</li>
	<% end %>
</ul>
<% end %>
<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<ul>
	<li><%= @user.username %></li>
	<li><%= @user.email %></li>
	<li><%= @user.password %></li>
<ul>

<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'All Users', users_path%>